apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: rentalstornacampsitesdotcommanagedcert
spec:
  domains:
    - rentals.tornacampsites.com
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: carrentaltornacampsitesdotcommanagedcert
spec:
  domains:
    - car-rental.tornacampsites.com
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: realestatetornacampsitesdotcommanagedcert
spec:
  domains:
    - real-estate.tornacampsites.com
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: hospitalitytornacampsitesdotcommanagedcert
spec:
  domains:
    - hospitality.tornacampsites.com
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: jewelrytornacampsitesdotcommanagedcert
spec:
  domains:
    - jewelry.tornacampsites.com
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: gymtornacampsitesdotcommanagedcert
spec:
  domains:
    - gym.tornacampsites.com
