apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: coderprabhu-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: coderprabhu-ip
    networking.gke.io/managed-certificates: "coderprabhudotcommanagedcert,coderprabhuapidotcommanagedcert,coderprabhuwwwdotcommanagedcert"
  labels:
    app: coderprabhu-ui
spec:
  rules:
  - host: www.coderprabhu.com
    http:
      paths:
        - path: /*
          backend:
            serviceName: coderprabhu-ui-backend
            servicePort: httpuiport
  - host: coderprabhu.com
    http:
      paths: 
        - path: /*      
          backend:
            serviceName: coderprabhu-ui-backend
            servicePort: httpuiport
  - host: api.coderprabhu.com
    http:
      paths:
        - path: /*
          backend:
            serviceName: coderprabhu-api-backend
            servicePort: httpapiport