apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: coderprabhu-ingress
  annotations:
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/ingress.global-static-ip-name: coderprabhu-ip
    networking.gke.io/managed-certificates: coderprabhudotcommanagedcert,coderprabhuapidotcommanagedcert
  labels:
    app: coderprabhu-app
spec:
  rules:
  - host: api.coderprabhu.com
    http:
      paths:
      - path: /*
        backend:
          serviceName: coderprabhu-api-backend
          servicePort: 8080
  - host: www.coderprabhu.com
    http:
      paths:
      - path: /*
        backend:
          serviceName: coderprabhu-ui-backend
          servicePort: 8080
  - host: coderprabhu.com
    http:
      paths:
      - path: /*
        backend:
          serviceName: coderprabhu-ui-backend
          servicePort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: coderprabhu-ui-backend
  labels:
    app: coderprabhu-ui
spec:
  type: NodePort
  selector:
    app: coderprabhu-ui
    tier: web
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: coderprabhu-api-backend
  labels:
    app: coderprabhu-api
spec:
  type: NodePort
  selector:
    app: coderprabhu-api
    tier: api
  ports:
  - port: 8080
    targetPort: 8080
