
curl http://coderprabhu.com
echo "-------------"
curl https://coderprabhu.com
echo "-------------"
curl http://www.coderprabhu.com
echo "-------------"
curl https://www.coderprabhu.com
echo "-------------"
curl http://api.coderprabhu.com
echo "-------------"
curl https://api.coderprabhu.com
echo "-------------"
curl http://api.coderprabhu.com/hello
echo "-------------"
curl https://api.coderprabhu.com/hello
echo "-------------"
curl http://api.coderprabhu.com/count
echo "-------------"
curl https://api.coderprabhu.com/count
echo "-------------"
